title: Anthony Sutton # your name (or website title) here
#logo: "/images/profile_pic.png?raw=true" # your photo (or logo) here
logo: "/images/profile_pic.png" # your photo (or logo) here
#description: > # your text below (remove <br> elements if you don't need line breaks)
#Screenshot from <i>Night on Earth</i>
#(P5 JS Wearables Prototype)
#<br><br>
#<a href="https://casagroupproject.github.io/">CASA Group Project Coursework Site</a> 
#<br><br>
#<a href="">View CV </a> 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
